# Use an official Python runtime as a parent image
FROM huggingface/transformers-pytorch-gpu

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .
    
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["uvicorn", "deploy-nlp-reddit:app", "--host", "0.0.0.0", "--port", "8000"]
