apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongo-prod-hpa
  namespace: mongodb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo-prod-deploy
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scale if CPU usage is above 70%
